src/objects/Custom_Log__c.object
<CustomObject>
    <description>As debug logs are only persisted if they are turned on, and only for 20 transactions.  This object will persist all code events to ensure full stack traceability even without debug enabled.</description>
    <fields>
        <fullName>Message__c</fullName>
        <description>The message recorded for this particular log event.  This will normally be the error thrown or some critical calculation output, list of objects used within the transaction etc.</description>
        <inlineHelpText>The message recorded for this particular log event.  This will normally be the error thrown or some critical calculation output, list of objects used within the transaction etc.</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>The name of the project that tis log applies too.</description>
        <inlineHelpText>The name of the project that tis log applies too.</inlineHelpText>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Stamp__c</fullName>
        <description>the timestamp that the log event is recorded at.  Logs are persisted at end of transaction so this field is the actual time of the event.</description>
        <inlineHelpText>the timestamp that the log event is recorded at.  Logs are persisted at end of transaction so this field is the actual time of the event.</inlineHelpText>
        <label>Time Stamp</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The level that this log is recorded at.</description>
        <inlineHelpText>The level that this log is recorded at.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debug</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Custom Log</label>
    <nameField>
        <displayFormat>CLOG-{00000}</displayFormat>
        <label>Custom Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomLogger.cls
/**
    * @Name:        CustomLogger 
    * @Description: Class to be used to persist custom logs (via the Custom_Log__c object) in Salesforce
    *                   Example of a info implementation :
    *                   CustomLogger.info(CustomLogger.PROJECT_AMEY_UU, 'Transaction was successfull');
    *
    *                   Example of logging an error :
    *                   try {
    *                       // do something
    *                   }
    *                   catch (System.exception ex) {
    *                           CustomLogger.error(CustomLogger.PROJECT_AMEY_UU, exception);
    *                   }
    *					
    *					When all events have been logged, alweays call save prior to execution enb.  Logs
    *					will only exist for the extent of the session in whic they are initiated
	*					
	*					CustomLogger.save();
    *
    * @author:      Jared Watson
    * @version:     1.0
    * Change Log 
    *
    * Date          author          Change Description
    * -----------------------------------------------------------------------------------
    * 19/07/2017    Jared Watson    Created Class
*/
public with sharing class CustomLogger {

    public static List<Custom_Log__c> customLogCache = new list<Custom_Log__c>();

    // Project Names 
    // - Please add additional project names here and then use the new constant
    // - NO STRINGS IN THE ACTUAL METHODS!
    // - this is so if you wish to change the actual Project label,
    //   you can do so in one place.
    public static final String PROJECT_AMEY_UU = 'Amey UU Water Meter Replacement';
    
    // Log types
    // - If you want to add more log types (such as Info etc...)
    //   please do so here and then reference the new constant in the methods
    // - NO STRINGS IN THE ACTUAL METHODS!
    // - Best practice is to also add the new value to the picklist on 
    //   the Custom Log object Custom_Log__c.Type__c
    private static final String LOG_TYPE_INFO   = 'Info';
    private static final String LOG_TYPE_DEBUG = 'Debug';
    private static final String LOG_TYPE_ERROR  = 'Error';
    
    
    public static void info(String projectName, String message) {
        log(projectName, LOG_TYPE_INFO, message);
    }
    
    public static void debug(String projectName, String message) {
        log(projectName, LOG_TYPE_DEBUG, message);
    }
    
    public static void error(String projectName, String message) { 
        log(projectName, LOG_TYPE_ERROR, message);
    }
    
    public static void error(String projectName, System.Exception ex) {
        log(projectName, LOG_TYPE_ERROR, ex.getMessage() + '; ' + ex.getTypeName() + '; ' + ex.getStackTraceString());
    }
    
    // Persists logs for current transaction
    public static void save() {
        if (customLogCache != null && customLogCache.size() > 0) {
            try {
                upsert customLogCache;
            }
            catch(System.exception ex) {
                // to be decided
            }
        }
    }
    
    // Create and populate a new Custom_Log__c object
    // and add it to the static list that will
    // be inserted at the end of a transaction
    private static void log(String projectName, String logType, String message) {
        Custom_Log__c log = new Custom_Log__c();
        
        // Do logging that is generic enough
        // to be applicable to all projects
        log.Project__c             = projectName;
        log.Time_Stamp__c          = getTimeStamp();
        log.Type__c                = logType;
        log.Message__c             = message;
        
        // Do logging that is specific to a particular project
        specificLogging(projectName, log);
        
        // Add to static list so that we do not have numerous DML statements 
        // throughout a transaction
        customLogCache.add(log);
        system.debug(message);
    }
    
    // Add an else statement to do do logging
    // specific to your project
    private static void specificLogging(String projectName, Custom_Log__c log) {
        if (projectName == PROJECT_AMEY_UU) {
            //add project specific data items here...
        }
    }
    
    // As logs are not immediately inserted 
    // (they are added to a list to be inserted at the end of a transaction)
    // so the CreatedDate field on Custom_Log__c is not useful to us.
    // We will generate a timestamp and populate the Time_Stamp__c field
    // so we can keep track of when individual logs were logged.
    private static String getTimeStamp() {
        return 'TS ' + String.valueOfGMT( System.now() );
    }
}